services:

  app: 
    hostname: app
    container_name: monitoring-service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${GOLANG_PORT}:${GOLANG_PORT}
    restart: always
    volumes:
      - ./:/app
    networks:
      - microservices-db-dev  # Consistent network name
    env_file:
      - .env

  nginx: 
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx-monitoring-service
    ports:
      - 8083:80
      - 8445:443
    depends_on:
      - app
    restart: unless-stopped
    tty: true
    volumes:
      - ./storage/:/app/storage/
      - ./static/:/app/static/
      # - ./docker/nginx/:/etc/nginx/conf.d
    networks:
      - microservices-db-dev  # Fixed: same network as app

volumes:
  app-volumes:

networks:
  microservices-db-dev:  # Simplified network definition
    name: microservices_dev_microservices-db-dev
    external: true