// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/SIM-MBKM/filestorage/storage"
	"github.com/google/wire"
	"gorm.io/gorm"
	"monitoring-service/config"
	"monitoring-service/controller"
	"monitoring-service/repository"
	"monitoring-service/service"
)

// Injectors from wire.go:

// InitializeAPI creates the full application with all dependencies
func InitializeAPI(db *gorm.DB, config2 *storage.Config, tokenManager *storage.CacheTokenManager, userManagementBaseURI string, brokerBaseURI config.BrokerbaseURI, registrationBaseURI config.RegistrationManagementbaseURI, asyncURIs []string) (*Application, error) {
	reportRepository := ProvideReportRepository(db)
	reportScheduleReposiotry := ProvideReportScheduleRepository(db)
	reportService := ProvideReportService(reportRepository, reportScheduleReposiotry, userManagementBaseURI, brokerBaseURI, asyncURIs, config2, tokenManager)
	reportController := ProvideReportController(reportService)
	reportScheduleService := ProvideReportScheduleService(reportScheduleReposiotry, userManagementBaseURI, registrationBaseURI, asyncURIs)
	reportScheduleController := ProvideReportScheduleController(reportScheduleService)
	transcriptRepository := ProvideTranscriptRepository(db)
	transcriptService := ProvideTranscriptService(transcriptRepository, userManagementBaseURI, registrationBaseURI, asyncURIs, config2, tokenManager)
	transcriptController := ProvideTranscriptController(transcriptService)
	syllabusRepository := ProvideSyllabusRepository(db)
	syllabusService := ProvideSyllabusService(syllabusRepository, userManagementBaseURI, registrationBaseURI, asyncURIs, config2, tokenManager)
	syllabusController := ProvideSyllabusController(syllabusService)
	application := newApplication(reportController, reportScheduleController, transcriptController, syllabusController)
	return application, nil
}

// wire.go:

// Application struct to hold all controllers
type Application struct {
	ReportController         controller.ReportController
	ReportScheduleController controller.ReportScheduleController
	TranscriptController     controller.TranscriptController
	SyllabusController       controller.SyllabusController
}

func newApplication(
	reportController controller.ReportController,
	reportScheduleController controller.ReportScheduleController,
	transcriptController controller.TranscriptController,
	syllabusController controller.SyllabusController,
) *Application {
	return &Application{
		ReportController:         reportController,
		ReportScheduleController: reportScheduleController,
		TranscriptController:     transcriptController,
		SyllabusController:       syllabusController,
	}
}

// Repository providers
func ProvideBaseRepository(db *gorm.DB) repository.BaseRepository {
	return repository.NewBaseRepository(db)
}

func ProvideReportRepository(db *gorm.DB) repository.ReportRepository {
	return repository.NewReportRepository(db)
}

func ProvideReportScheduleRepository(db *gorm.DB) repository.ReportScheduleReposiotry {
	return repository.NewReportScheduleRepository(db)
}

func ProvideTranscriptRepository(db *gorm.DB) repository.TranscriptRepository {
	return repository.NewTranscriptRepository(db)
}

func ProvideSyllabusRepository(db *gorm.DB) repository.SyllabusRepository {
	return repository.NewSyllabusRepository(db)
}

// Service providers
func ProvideFileService(config2 *storage.Config, tokenManager *storage.CacheTokenManager) *service.FileService {
	return service.NewFileService(config2, tokenManager)
}

func ProvideUserManagementService(
	userManagementBaseURI string,
	asyncURIs []string,
) *service.UserManagementService {
	return service.NewUserManagementService(userManagementBaseURI, asyncURIs)
}

func ProvideReportService(
	reportRepo repository.ReportRepository,
	reportScheduleRepo repository.ReportScheduleReposiotry,
	userManagementBaseURI string,
	brokerBaseURI config.BrokerbaseURI,
	asyncURIs []string, config2 *storage.Config,
	tokenManager *storage.CacheTokenManager,
) service.ReportService {
	return service.NewReportService(
		reportRepo,
		reportScheduleRepo,
		userManagementBaseURI,
		string(brokerBaseURI),
		asyncURIs, config2, tokenManager,
	)
}

func ProvideReportScheduleService(
	reportScheduleRepo repository.ReportScheduleReposiotry,
	userManagementBaseURI string,
	registrationBaseURI config.RegistrationManagementbaseURI,
	asyncURIs []string,
) service.ReportScheduleService {
	return service.NewReportScheduleService(reportScheduleRepo, userManagementBaseURI, string(registrationBaseURI), asyncURIs)
}

func ProvideTranscriptService(
	transcriptRepo repository.TranscriptRepository,
	userManagementBaseURI string,
	registrationBaseURI config.RegistrationManagementbaseURI,
	asyncURIs []string, config2 *storage.Config,
	tokenManager *storage.CacheTokenManager,
) service.TranscriptService {
	return service.NewTranscriptService(
		transcriptRepo,
		userManagementBaseURI,
		string(registrationBaseURI),
		asyncURIs, config2, tokenManager,
	)
}

func ProvideSyllabusService(
	syllabusRepo repository.SyllabusRepository,
	userManagementBaseURI string,
	registrationBaseURI config.RegistrationManagementbaseURI,
	asyncURIs []string, config2 *storage.Config,
	tokenManager *storage.CacheTokenManager,
) service.SyllabusService {
	return service.NewSyllabusService(
		syllabusRepo,
		userManagementBaseURI,
		string(registrationBaseURI),
		asyncURIs, config2, tokenManager,
	)
}

// Controller providers
func ProvideReportController(reportService service.ReportService) controller.ReportController {
	return *controller.NewReportController(reportService)
}

func ProvideReportScheduleController(reportScheduleService service.ReportScheduleService) controller.ReportScheduleController {
	return *controller.NewReportScheduleController(reportScheduleService)
}

func ProvideTranscriptController(transcriptService service.TranscriptService) controller.TranscriptController {
	return *controller.NewTranscriptController(transcriptService)
}

func ProvideSyllabusController(syllabusService service.SyllabusService) controller.SyllabusController {
	return *controller.NewSyllabusController(syllabusService)
}

// Provider sets
var (
	RepositorySet = wire.NewSet(
		ProvideBaseRepository,
		ProvideReportRepository,
		ProvideReportScheduleRepository,
		ProvideTranscriptRepository,
		ProvideSyllabusRepository,
	)

	ServiceSet = wire.NewSet(
		ProvideFileService,
		ProvideUserManagementService,
		ProvideReportService,
		ProvideReportScheduleService,
		ProvideTranscriptService,
		ProvideSyllabusService,
	)

	ControllerSet = wire.NewSet(
		ProvideReportController,
		ProvideReportScheduleController,
		ProvideTranscriptController,
		ProvideSyllabusController,
	)

	AllSet = wire.NewSet(
		RepositorySet,
		ServiceSet,
		ControllerSet,
	)
)
