// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/SIM-MBKM/filestorage/storage"
	"github.com/google/wire"
	"gorm.io/gorm"
	"monitoring-service/controller"
	"monitoring-service/repository"
	"monitoring-service/service"
)

// Injectors from wire.go:

// InitializeAPI creates the full application with all dependencies
func InitializeAPI(db *gorm.DB, config *storage.Config, tokenManager *storage.CacheTokenManager, userManagementBaseURI string, asyncURIs []string) (*Application, error) {
	reportRepository := ProvideReportRepository(db)
	reportScheduleReposiotry := ProvideReportScheduleRepository(db)
	reportService := ProvideReportService(reportRepository, reportScheduleReposiotry, userManagementBaseURI, asyncURIs, config, tokenManager)
	reportController := ProvideReportController(reportService)
	reportScheduleService := ProvideReportScheduleService(reportScheduleReposiotry, userManagementBaseURI, asyncURIs)
	reportScheduleController := ProvideReportScheduleController(reportScheduleService)
	transcriptRepository := ProvideTranscriptRepository(db)
	transcriptService := ProvideTranscriptService(transcriptRepository, userManagementBaseURI, asyncURIs, config, tokenManager)
	transcriptController := ProvideTranscriptController(transcriptService)
	application := newApplication(reportController, reportScheduleController, transcriptController)
	return application, nil
}

// wire.go:

// Application struct to hold all controllers
type Application struct {
	ReportController         controller.ReportController
	ReportScheduleController controller.ReportScheduleController
	TranscriptController     controller.TranscriptController
}

func newApplication(
	reportController controller.ReportController,
	reportScheduleController controller.ReportScheduleController,
	transcriptController controller.TranscriptController,
) *Application {
	return &Application{
		ReportController:         reportController,
		ReportScheduleController: reportScheduleController,
		TranscriptController:     transcriptController,
	}
}

// Repository providers
func ProvideBaseRepository(db *gorm.DB) repository.BaseRepository {
	return repository.NewBaseRepository(db)
}

func ProvideReportRepository(db *gorm.DB) repository.ReportRepository {
	return repository.NewReportRepository(db)
}

func ProvideReportScheduleRepository(db *gorm.DB) repository.ReportScheduleReposiotry {
	return repository.NewReportScheduleRepository(db)
}

func ProvideTranscriptRepository(db *gorm.DB) repository.TranscriptRepository {
	return repository.NewTranscriptRepository(db)
}

// Service providers
func ProvideFileService(config *storage.Config, tokenManager *storage.CacheTokenManager) *service.FileService {
	return service.NewFileService(config, tokenManager)
}

func ProvideUserManagementService(
	userManagementBaseURI string,
	asyncURIs []string,
) *service.UserManagementService {
	return service.NewUserManagementService(userManagementBaseURI, asyncURIs)
}

func ProvideReportService(
	reportRepo repository.ReportRepository,
	reportScheduleRepo repository.ReportScheduleReposiotry,
	userManagementBaseURI string,
	asyncURIs []string,
	config *storage.Config,
	tokenManager *storage.CacheTokenManager,
) service.ReportService {
	return service.NewReportService(
		reportRepo,
		reportScheduleRepo,
		userManagementBaseURI,
		asyncURIs,
		config,
		tokenManager,
	)
}

func ProvideReportScheduleService(
	reportScheduleRepo repository.ReportScheduleReposiotry,
	userManagementBaseURI string,
	asyncURIs []string,
) service.ReportScheduleService {
	return service.NewReportScheduleService(reportScheduleRepo, userManagementBaseURI, asyncURIs)
}

func ProvideTranscriptService(
	transcriptRepo repository.TranscriptRepository,
	userManagementBaseURI string,
	asyncURIs []string,
	config *storage.Config,
	tokenManager *storage.CacheTokenManager,
) service.TranscriptService {
	return service.NewTranscriptService(
		transcriptRepo,
		userManagementBaseURI,
		asyncURIs,
		config,
		tokenManager,
	)
}

// Controller providers
func ProvideReportController(reportService service.ReportService) controller.ReportController {
	return *controller.NewReportController(reportService)
}

func ProvideReportScheduleController(reportScheduleService service.ReportScheduleService) controller.ReportScheduleController {
	return *controller.NewReportScheduleController(reportScheduleService)
}

func ProvideTranscriptController(transcriptService service.TranscriptService) controller.TranscriptController {
	return *controller.NewTranscriptController(transcriptService)
}

// Provider sets
var (
	RepositorySet = wire.NewSet(
		ProvideBaseRepository,
		ProvideReportRepository,
		ProvideReportScheduleRepository,
		ProvideTranscriptRepository,
	)

	ServiceSet = wire.NewSet(
		ProvideFileService,
		ProvideUserManagementService,
		ProvideReportService,
		ProvideReportScheduleService,
		ProvideTranscriptService,
	)

	ControllerSet = wire.NewSet(
		ProvideReportController,
		ProvideReportScheduleController,
		ProvideTranscriptController,
	)

	AllSet = wire.NewSet(
		RepositorySet,
		ServiceSet,
		ControllerSet,
	)
)
